services:
  lgtm:
    image: grafana/otel-lgtm:latest
    ports:
      - "3000:3000"   # Grafana
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "9090:9090"   # Prometheus
      - "4040:4040"   # Pyroscope/Profiling (se habilitado)
    environment:
      ENABLE_LOGS_ALL: "true"

  rolldice:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4318
      OTEL_EXPORTER_OTLP_INSECURE: "true"
      OTEL_METRIC_EXPORT_INTERVAL: "5000"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=rolldice,service.instance.id=docker:8081"
    ports:
      - "8081:8081"
    depends_on:
      - lgtm

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4318
      OTEL_EXPORTER_OTLP_INSECURE: "true"
      OTEL_METRIC_EXPORT_INTERVAL: "5000"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=gateway,service.instance.id=docker:8080"
      ROLLDICE_URL: http://rolldice:8081
    ports:
      - "8080:8080"
    depends_on:
      - lgtm
      - rolldice